AllCops:
  Exclude:
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
